spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: true
server:
  port: 8080